# Nome da aplicação

spring.application.name=pulsepost

# Porta do server

server.port=8080


# Banco de dados PostgreSQL em localhost

spring.datasource.url=jdbc:postgresql://localhost:5432/pulse_post_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update


# Chave Secreta
api.security.token.secret=${JWT_SECRET:my-secret-key}

# Cloudinary
cloudinary.cloud-name=dk0mrcf6d
cloudinary.api-key=339232517655663
cloudinary.api-secret=U0Lqo9ApC45womuh-shhKxv7nPc

# Configurar o tamanho máximo do arquivo de upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

